<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>array, for 연습문제</title>
	</head>
	<body>
		<script>
			var 출석부 = ["흥민", "흥민", "영희", "철수", "철수", "재석"];

			function 이름찾기2(name) {
				for (var i = 0; i < 출석부.length; i++) {
					if (name == 출석부[i]) {
						console.log("있어요");
						return;
					}
				}
			}

			이름찾기2("철수");

			function 이름찾기(name) {
				출석부.forEach(i => {
					if (name == i) {
						console.log("있어요");
						// throw "break";
						//이건 맞는 방법은 아니고 정확히는 try catch를 이용해서 exception을 줘야하는거같다.
					}
				});
			}
			이름찾기("흥민");
			// 이름찾기("명수");
			// indexOf, find 이런거 나중에찾아보기

			/*구구단 만들기*/

			//내가 한 것
			/*
			for (i = 1; i < 10; i++) {
				function 곱(a) {
					a = i * a;
					return a;
				}
				console.log(곱(1));
				console.log(곱(2));
				console.log(곱(3));
				console.log(곱(4));
				console.log(곱(5));
				console.log(곱(6));
				console.log(곱(7));
				console.log(곱(8));
				console.log(곱(9));
			}
			   */
			//다른방법
			for (let i = 1; i < 10; i++) {
				for (let a = 1; a < 10; a++) {
					console.log(i * a);
				}
			}

			function score(arr, b) {
				let result = 0;
				for (let i = 0; i < arr.length; i++) {
					result += arr[i];
				}
				let aver = result / arr.length;
				console.log(aver);
				if (aver > b) {
					console.log(`평균보다 ${aver - b}점이 올랐네요!`);
				} else if (aver < b) {
					console.log(`평균보다 ${aver - b}점이 떨어졌네요 재수추천`);
				}
			}
			score([10, 20, 30, 40, 50], 40);
			// score([40, 40, 40], 20);
		</script>
	</body>
</html>
